INSERT INTO medical_center VALUES('1556', 'Medical Center 1','District 1','Ben Nghe','Ngo Gia Tu','51');
INSERT INTO medical_center VALUES('3655', 'Medical Center 2','District 1','Ben Thanh','Ly Thuong Kiet','14');
INSERT INTO medical_center VALUES('3465', 'Medical Center 3','District 1','Co Giang','Quang Trung','24');
INSERT INTO medical_center VALUES('5521', 'Medical Center 4','District 1','Cau Kho','Ngo Tat To','23');
INSERT INTO medical_center VALUES('6241', 'Medical Center 5','District 1','Ong Lanh','Nguyen Thuong Hien','58');
INSERT INTO medical_center VALUES('4423', 'Medical Center 6','District 1','Da Kao','Phan Dang Luu','76');
INSERT INTO medical_center VALUES('4568', 'Medical Center 7','District 2','An Phu','Tran Hung Dao','71');
INSERT INTO medical_center VALUES('1462', 'Medical Center 8','District 2','Thao Dien','Hoang Hoa Tham','35');
INSERT INTO medical_center VALUES('5235', 'Medical Center 9','District 2','An Khanh','Nguyen Van Dau','1');
INSERT INTO medical_center VALUES('6685', 'Medical Center 10','District 2','Binh An','Nguyen Minh Triet','2');
INSERT INTO medical_center VALUES('4544', 'Medical Center 11','District 2','Thu Khiem','CMT8','25');
INSERT INTO medical_center VALUES('2878', 'Medical Center 12','District 2','An Loi Dong','3 Thang 2','35');
INSERT INTO medical_center VALUES('1111', 'Medical Center 13','District 2','Cat Lai','Dinh Tien Hoang','21');
INSERT INTO medical_center VALUES('5647', 'Medical Center 14','District 3','1','Co Giang','66');
INSERT INTO medical_center VALUES('6544', 'Medical Center 15','District 3','2','Co Bac','63');
INSERT INTO medical_center VALUES('4565', 'Medical Center 16','District 3','3','Pauster','68');
INSERT INTO medical_center VALUES('7877', 'Medical Center 17','District 3','4','Nguyen Trai','46');
INSERT INTO medical_center VALUES('8788', 'Medical Center 18','District 3','5','Nguyen Kim','49');
INSERT INTO medical_center VALUES('1544', 'Medical Center 19','District 3','13','Vo Van Kiet','41');
INSERT INTO medical_center VALUES('2445', 'Medical Center 20','District 3','Vo Thi Sau','Nguyen Thi Minh Khai','43');